title: Wayne Irving's Blog
author: Wayne Irving
email: thene1isinfini1e@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just a website about me nothing special :P
# social links
twitter_username: fuck twitter
github_username:  WayneIrving

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
